### ISSUE TITLE
Numeric input broken on Safari for macOS

### ISSUE THREAD

**Issue by qauff** [drac94/react-auth-code-input#53] opened 2022-06-26 23:42 UTC
I am able to enter non-number values in Safari on macOS, even when `allowedCharacters` is set to `numeric`. It looks like when you enter a non numeric value, onChange is not triggered either.

**Comment by PurrBiscuit** [comment] 2022-06-29 14:25
I'm seeing unexpected behavior with the `numeric` set of `allowedCharacters` as well in Firefox.  If I just enter numbers it works fine.  I tried to enter a letter, expecting it to fail that validation and for no input to be registered, but it does allow the letter to be entered into the input field.  It also seems to ignore the `maxLength=1` attribute on the element and allows me to continue entering additional characters in the input.  I'm also unable to delete the items in the input once it begins with a letter and starts to concatenate additional values to that input.  Here's a screencast showing the behavior I'm seeing with `allowedCharacters` set to `numeric`:

<p align="center">
  <img src="https://user-images.githubusercontent.com/4661524/176460606-5f06b752-a617-4757-88f5-db5ad9436558.gif" />
</p>

**Comment by drac94** [comment] 2022-06-29 18:45
Hi @qauff @PurrBiscuit thanks for raising the issue, I think I've found the cause, when you write non-numeric values in an input of type number, the `onChange` handler is not called 😢  thus not validating anything nor calling the callback function, I found this possible solution but I need to do more tests and see if this may not be a breaking change for older implementations. https://github.com/facebook/react/issues/16554#issuecomment-657075924

**Comment by qauff** [comment] 2022-06-29 18:53
There's another [library](https://github.com/devfolioco/react-otp-input) that actually uses `tel` and it seems to work in Safari and Firefox too.

**Comment by qauff** [comment] 2022-07-08 01:25
@drac94 awesome! I see there's a new commit in `master` that fixes this issue. And the demo site works as intended now in firefox and safari!!! thank you so much!

Looking forward to the release to npm 🙏

**Comment by drac94** [comment] 2022-07-08 15:26
@qauff I was trying to solve the other issue to include it in the new version but it seems like it requires more effort than I thought, I just released the new version on npm, cheers!

**Comment by drac94** [comment] 2022-07-08 15:29
Fixed in #54 #55

**Closed by drac94** 2022-07-08 15:29 UTC
Labels: bug
